#!/usr/bin/env node
// Writes src/config.secrets.js from TWITCH_CLIENT_ID (.env or env var). Do not commit output.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/config.secrets.js');

const readDotEnv = () => {
  const path = join(ROOT, '.env');
  if (!existsSync(path)) return '';
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const match = trimmed.match(/^TWITCH_CLIENT_ID\s*=\s*(.+)$/);
    if (!match) continue;
    return match[1].trim().replace(/^['"]|['"]$/g, '');
  }
  return '';
};

const clientId = process.env.TWITCH_CLIENT_ID || readDotEnv() || '';

if (!clientId && existsSync(OUT)) {
  console.warn('inject-secrets: TWITCH_CLIENT_ID empty — keeping existing config.secrets.js');
  process.exit(0);
}

if (!clientId && process.env.CI === 'true') {
  console.error('inject-secrets: TWITCH_CLIENT_ID is required in CI (GitHub secret).');
  process.exit(1);
}

writeFileSync(
  OUT,
  `// Auto-generated by scripts/inject-secrets.mjs — do not commit.
// Set TWITCH_CLIENT_ID in .env (see .env.example) or as an environment variable.

export const CLIENT_ID = ${JSON.stringify(clientId)};
`,
);

if (!clientId) {
  console.warn('inject-secrets: TWITCH_CLIENT_ID is empty — OAuth will not work until .env is set.');
} else {
  console.log('inject-secrets: wrote src/config.secrets.js');
}
